### ISSUE TITLE
지역날씨뷰 리팩토링

### ISSUE THREAD

**Issue by lenamin** [iDrogba/WeatherApp#19]
##   todo
- [x] 주간 날씨 불러올 수 있는 최대일수 불러오기 
- [x] 주간 날씨 최저 최고 기온 데이터 불러오기 
- [x] 요일 형식 수정하기
